### ISSUE TITLE
横幅增强

### ISSUE THREAD

**Issue by lion-no-back** [sawhney17/logseq-banners-plugin#9]
Hello, I like the effect of this banner very much. I don’t know if it can be designed with rounded corners and borders.

**Comment by yoyurec** [comment]
you can do something like this
```css
.is-banner-active #main-content-container::before {
    border-radius: 10px 10px 0 0;
}
```
![image](https://user-images.githubusercontent.com/137919/177014034-b3c9f52d-9b13-4ce8-ac86-7829c3370c42.png)
